dubbo:
  scan:
    base-packages: cn.com.do1cloud.example.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    address: nacos://local143:8848
  cloud:
    subscribed-services: consumer
  consumer:
    check: false